default_install_hook_types = ["pre-commit"]
default_stages = ["pre-commit"]

exclude = "^target/"

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-merge-conflict" },
  { id = "check-toml" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "make-test"
name = "make test"
language = "system"
entry = "make test"
pass_filenames = false
types = ["rust"]
